name: Lint control

on:
  pull_request:
  push:
    branches: [master]

env:
  NODE_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
